/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: czrpvLfdRGgF3py81DP1YF

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantssZs9YzRzYw63 } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: sZS9YzRzYW63/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantssZs9YzRzYw63
});
